baseURL: "https://pascalmichaillat.org/hugo-website/" 
title: Kazuki Fujii
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
    tag: tags

menu:
    main:
        - name: Publications
          url: publications/
          weight: 6

params:
    description: "This website hosts Kazuki Fujii's research papers, books, course materials, data, curriculum vitae, and contact information."
    author: Kazuki Fujii
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["books","courses","papers","data"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Kazuki Fujii
          subtitle: "Kazuki Fujii is an incoming PhD student at the Institute of Science Tokyo (formerly Tokyo Tech). He is a core contributor to the [Swallow Project](https://swallow-llm.github.io/index.en.html), leading the development of open Japanese-English bilingual LLMs.</br></br>
          His research sits at the intersection of HPC and Machine Learning, with a focus on large-scale distributed training and low-precision optimization (FP8/NVFP4) using Megatron-LM and TransformerEngine. He also researches data-centric approaches to improve reasoning capabilities in LLMs. His recent work on rewriting pre-training data for Math and Code was accepted to ICLR 2026.</br></br>
          He will be presenting his work on Swallow LLM at NVIDIA GTC 2026. He is currently seeking research internship opportunities in the US.
          <br/><br/>
          Contact: kazuki.fujii [at] rio.scrc.iir.isct.ac.jp
          "
          imageUrl: "picture.png"
          imageWidth: 160
          imageHeight: 160
          buttons:
            - name: CV
              url: cv.pdf
            - name: Publications
              url: publications/
            - name: Blog(Japanese)
              url: https://zenn.dev/kaz20

    socialIcons:
        - name: CV
          url: cv.pdf
        - name: LinkedIn
          url: https://www.linkedin.com/in/kazuki-fujii/
        - name: Google Scholar
          url: https://scholar.google.co.jp/citations?user=jHXLs2wAAAAJ&hl=en
        - name: GitHub
          url: https://github.com/okoge-kaz
        - name: Twitter
          url: https://x.com/okoge_kaz
        - name: Bluesky
          url: https://bsky.app/profile/kazukifujii.bsky.social

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Kazuki Fujii"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
